fix：fix a wrong converted value
kubeedge/kubeedge pull request #2748
Opened 2021-03-30 09:02 UTC by coldy1992

When the register type is coilregister, the converted value is wrong

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2021-03-30 11:25 UTC, fisherxu reviewed
@coldy1992 Thanks for your contribution, now the modbus-go has been moved to kubeedge/mapper-go repo, please open the PR there.

2021-04-02 02:14 UTC, wzshiming requested changes

2021-04-02 02:14 UTC, wzshiming commented on mappers/modbus-go/device/device.go
> +
```suggestion
	var valueInt int64
	switch val := value.(type) {
	case int64:
		valueInt = val
	case bool:
		if val {
			valueInt = 1
		} else {
			valueInt = 0
		}
	}
```

2021-04-12 01:32 UTC, fisherxu commented
Will close the pr, please refer to comment: https://github.com/kubeedge/kubeedge/pull/2748#pullrequestreview-624141720

Please reopen it if there's any issue.

/close

2021-04-12 01:32 UTC, closed without merging