fix unhandled transaction error
kubeedge/kubeedge pull request #4091
Opened 2022-08-04 06:31 UTC by elpsyr

Signed-off-by: crui <crui@relaper.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix some unhandled transaction error.
If the error caused by rollback is not captured, it will be commit successfully.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-08-04 06:44 UTC, closed without merging

2022-08-04 06:45 UTC, elpsyr commented
golint err with spelling mistack: deviceid to deviceID

2022-08-04 06:46 UTC, gy95 requested changes
seems ok

2022-08-04 06:46 UTC, gy95 commented on edge/pkg/devicetwin/dtclient/device_db.go
> +				klog.Errorf("transaction rollback failed: %v", err)
errRollback

2022-08-04 06:46 UTC, gy95 commented on edge/pkg/devicetwin/dtclient/device_db.go
> +				klog.Errorf("transaction rollback failed: %v", err)
ditto, replace err with errRollback
and the other logs need fixing

2022-08-05 03:41 UTC, elpsyr commented on edge/pkg/devicetwin/dtclient/device_db.go
> +				klog.Errorf("transaction rollback failed: %v", err)
oh,sorry.I will correct it right now :)