Change the print helm chart resources YAML command name keadm generate to keadm manifest.
kubeedge/kubeedge pull request #5462
Opened 2024-03-11 14:56 UTC by luomengY

… to keadm manifest.

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
![image](https://github.com/kubeedge/kubeedge/assets/110345347/0bd8dbfd-3e61-4e4b-b35a-72a039e41269)
**Which issue(s) this PR fixes**:

Fixes #https://github.com/kubeedge/kubeedge/issues/5317

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2024-03-12 13:12 UTC, wbc6080 reviewed
Seems this PR and 5463, 5461 are aimed to solve #5317 together, so you'd better change the "Which issue(s) this PR fixes:" content in PR description. Otherwise, any one of these PRs after being merged will cause the issue to be closed . Maybe you can use "A part of #5317"

2024-03-14 05:38 UTC, luomengY commented
> Seems this PR and 5463, 5461 are aimed to solve #5317 together, so you'd better change the "Which issue(s) this PR fixes:" content in PR description. Otherwise, any one of these PRs after being merged will cause the issue to be closed . Maybe you can use "A part of #5317"

ok

2024-03-26 03:18 UTC, WillardHu requested changes

2024-03-26 03:18 UTC, WillardHu commented on keadm/cmd/keadm/app/cmd/cloud/manifest.go
>  		Long:    cloudManifestGenerateLongDescription,
Modify and clean up long messages

2024-03-26 07:12 UTC, luomengY commented on keadm/cmd/keadm/app/cmd/cloud/manifest.go
>  		Long:    cloudManifestGenerateLongDescription,
I have Modified it.

2024-03-26 07:55 UTC, WillardHu commented
/lgtm

2024-04-15 07:49 UTC, fisherxu reviewed
/approve

2024-04-15 07:49 UTC, merged