Refactor the command reset to third-level commands, like: keamd reset
kubeedge/kubeedge pull request #5463
Opened 2024-03-12 06:19 UTC by luomengY

cloud and keadm reset edge. If uses keadm rest, both the cloud and the edge will be reset.`

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
![image](https://github.com/kubeedge/kubeedge/assets/110345347/8934892a-7dbc-470b-8059-ec55ce66aa32)

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubeedge/kubeedge/issues/5317

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2024-03-26 03:10 UTC, WillardHu requested changes

2024-03-26 03:10 UTC, WillardHu commented on keadm/cmd/keadm/app/cmd/reset_others.go
> -			if err := RemoveMqttContainer(reset.Endpoint, ""); err != nil {
Maybe we still need to consider the case of removing mqtt.

2024-03-26 03:10 UTC, WillardHu commented on keadm/cmd/keadm/app/cmd/edge/reset_other.go
> +keadm reset
keadm reset edge

2024-03-26 09:03 UTC, WillardHu commented
/lgtm

2024-04-17 06:53 UTC, fisherxu commented on keadm/cmd/keadm/app/cmd/cloud/reset.go
> +package cloud
Add the License header

2024-04-20 07:29 UTC, fisherxu reviewed
/approve
/assign @WillardHu

2024-04-22 04:51 UTC, WillardHu commented
/lgtm

2024-04-22 04:52 UTC, merged