Fix the status reporting of device to avoid issues defined by twin.
kubeedge/kubeedge pull request #5467
Opened 2024-03-14 05:30 UTC by luomengY

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
In version v1.15.0, we removed the content of the user-defined status module. When deploying a device, the Twins reported by the device status are empty. In this case, we need to create Twins, otherwise the status will not have any content.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
@wbc6080 
**Does this PR introduce a user-facing change?**:

```release-note

```

2024-03-27 07:49 UTC, wbc6080 commented
LGTM  thanks

2024-03-27 08:35 UTC, WillardHu requested changes

2024-03-28 05:07 UTC, luomengY commented on cloud/pkg/devicecontroller/controller/upstream.go
> +	return nil
> The return value nil is not processed at the call when the twin doesn't match any properties, is that expected?

When twin returns to nil, a new twin will be created：
			......
			twin := findTwinByName(twinName, deviceStatus)
			if twin != nil {
				return twin
			}
			twin = &v1beta1.Twin{
				PropertyName: twinName,
			}
			......

2024-03-28 05:07 UTC, luomengY commented on cloud/pkg/devicecontroller/controller/downstream.go
> +	var newTwins []v1beta1.Twin
ok

2024-03-29 01:31 UTC, WillardHu commented on cloud/pkg/devicecontroller/controller/upstream.go
> +	return nil
ok

2024-03-29 01:32 UTC, WillardHu commented
/lgtm

2024-04-10 09:47 UTC, wbc6080 commented
@Shelley-BaoYue @zhiyingfang2022 Please help add this pr to version 1.17, thanks

2024-04-11 09:06 UTC, zhiyingfang2022 commented
> @Shelley-BaoYue @zhiyingfang2022 Please help add this pr to version 1.17, thanks

ok,done.

2024-04-17 06:13 UTC, fisherxu reviewed
/approve

2024-04-17 06:13 UTC, merged