Proposal:Keadm Tool Enhancement
kubeedge/kubeedge pull request #5574
Opened 2024-04-28 07:15 UTC by HT0403

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Keadm(KubeEdge installation tool) now only supports configuring a subset of parameters during EdgeCore installation. We would like to support specifying parameters using --set or directly using an existing local configuration file to achieve full parameter configuration and meet the users' requirements.
**Which issue(s) this PR fixes**:

Fixes #5563 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2024-04-29 10:22 UTC, fisherxu reviewed
/assign @WillardHu

2024-05-14 06:39 UTC, WillardHu commented
Add some design contents about how to add a flag `set` to the keadm and applied to the edgecore config.

2024-05-15 08:31 UTC, WillardHu requested changes

2024-05-15 08:31 UTC, WillardHu commented on docs/proposals/Keadm Tool Enhancement.md
> +### **The frame design drawing is as follows**：
```markdown
### The frame design drawing is as follows
```

2024-05-15 08:31 UTC, WillardHu commented on docs/proposals/Keadm Tool Enhancement.md
> + ###  **Design contents about how to add a flag `set` **
```markdown
### Design contents about how to add a flag `set`
```

2024-05-15 08:31 UTC, WillardHu commented on docs/proposals/Keadm Tool Enhancement.md
> +```go
1. You need add a flag define in the AddJoinOtherFlags() function, this function is both in file join_others.go and join_windows.go, you can refer to https://github.com/kubeedge/kubeedge/blob/7a81f8a3e603510b4d9b7dfedf6203c3cdfa83fd/keadm/cmd/keadm/app/cmd/cloud/init.go#L107
2. You need parse set slice values to edgeCoreConfig instance after it was initialized in the createEdgeConfigFiles() function this function is both in file join_others.go and join_windows.go too, you can refer to https://github.com/kubeedge/kubeedge/blob/7a81f8a3e603510b4d9b7dfedf6203c3cdfa83fd/keadm/cmd/keadm/app/cmd/edge/join_others.go#L168

2024-05-16 01:26 UTC, WillardHu requested changes

2024-05-16 01:26 UTC, WillardHu commented on docs/proposals/Keadm Tool Enhancement.md
> + ###  Design contents about how to add a flag `set`
Add some examples for `keadm join --set`

2024-05-22 06:03 UTC, WillardHu approved these changes

2024-05-22 06:04 UTC, merged

2024-05-22 06:15 UTC, WillardHu commented
Sorry, I approve my request changes, but the label approved have been added... 😂

2024-05-22 08:01 UTC, fisherxu commented
> Sorry, I approve my request changes, but the label approved have been added... 😂

All right, if there's any issue, just fix it in follow up PRs :)